build:
  main: main.go
  binary: geb
  ldflags: -s -w -X main.builddate={{.Date}}
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
    # - freebsd
    # - netbsd
    # - openbsd
    # - dragonfly
  goarch:
    - amd64
    - 386
    - arm
    - arm64
  ignore:
    - goos: openbsd
      goarch: arm
      goarm: 6

fpm:
  formats:
      - deb
  vendor: "hofstadter.io"
  homepage: "https://geb.hofstadter.io/"
  maintainer: "Tony Worm <verdverm@gmail.com>"
  description: "A DSL and Code Generation framework built with love in GoLang."
  license: "BSD 3-Clause"
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: "{{.Binary}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  replacements:
    amd64: 64bit
    386: 32bit
    arm: ARM
    arm64: ARM64
    darwin: macOS
    linux: Linux
    windows: Windows
    openbsd: OpenBSD
    netbsd: NetBSD
    freebsd: FreeBSD
    dragonfly: DragonFlyBSD
  files:
    - readme.md
    - LICENSE.md

git:
  short_hash: true

release:
  draft: true
