language: go

go:
  - 1.6
  - 1.7.x

install: true

script:
  - go build main.go
  - geb gen
  - make clone
  - make profit
  - make serious-profit
  - go build main.go
  - geb gen
  - make clone
  - make profit
  - make serious-profit
  - go build main.go


