type-list:
  name: "gen-config-types"
  list:
    - name: Config
      kabob: true
      fields:
        - name: Name
          type: string
        - name: Version
          type: string
        - name: About
          type: string
        - name: Type
          type: string
        - name: Language
          type: string
        - name: Dependencies
          type: Dependencies
        - name: TemplateConfigs
          type: array:TemplateConfig
        - name: OutputDir
          type: string

    - name: TemplateConfig
      kabob: true
      fields:
        - name: Name
          type: string
        - name: Field
          type: string
        - name: Flatten
          type: int
        - name: Templates
          type: array:TemplateRenderPair

    - name: TemplateRenderPair
      kabob: true
      fields:
        - name: When
          type: string
        - name: Unless
          type: string
        - name: Field
          type: string
        - name: Flatten
          type: int
        - name: In
          type: string
        - name: Out
          type: string
        - name: Extra
          type: array:string

    - name: Dependencies
      kabob: true
      fields:
        - name: Designs
          type: array:TemplateConfig
        - name: Generators
          type: array:GeneratorConfig

    - name: GeneratorConfig
      kabob: true
      fields:
        - name: Dsl
          type: string
          required: true
        - name: Gen
          type: array:string
        - name: OutputDir
          type: string

