type-list:
  name: "gen-config-types"
  list:
    - name: config
      kabob: true
      fields:
        - name: name
          type: string
        - name: version
          type: string
        - name: about
          type: string
        - name: type
          type: string
        - name: language
          type: string
        - name: dependencies
          type: dependencies
        - name: template-configs
          type: array:template-config
        - name: output-dir
          type: string

    - name: template-config
      kabob: true
      fields:
        - name: name
          type: string
        - name: field
          type: string
        - name: flatten
          type: int
        - name: templates
          type: array:template-render-pair

    - name: template-render-pair
      kabob: true
      fields:
        - name: when
          type: string
        - name: in
          type: string
        - name: out
          type: string

    - name: dependencies
      kabob: true
      fields:
        - name: designs
          type: array:dependent-designs
        - name: generators
          type: array:generator-config

    - name: dependent-designs
      kabob: true
      fields:
        - name: name
          type: string
        - name: field
          type: string
        - name: when
          type: string
        - name: in
          type: string
        - name: out
          type: string

    - name: generator-config
      kabob: true
      fields:
        - name: dsl
          type: string
          required: true
        - name: gen
          type: array:string
        - name: output-dir
          type: string

