type-list:
  name: "gen-config-types"
  list:
    - name: config
      version: "0.0.1"
      fields:
        - name: name
          type: string
          required: true
        - name: version
          type: string
          required: true
        - name: about
          type: string
        - name: type
          type: string
          required: true
        - name: language
          type: string
          required: true
        - name: template-configs
          type: array:template-config
        - name: output-dir
          type: string

    - name: template-config
      version: "0.0.1"
      fields:
        - name: name
          type: string
          required: true
        - name: field
          type: string
          required: true
        - name: templates
          type: array:template-render-pair

    - name: template-render-pair
      version: "0.0.1"
      fields:
        - name: in
          type: string
          required: true
        - name: out
          type: string
          required: true

