type:
  name: "Config"
  kabob: true
  version: "0.0.1"
  fields:
    - name: Name
      type: string
      required: true
    - name: Version
      type: string
      required: true
    - name: About
      type: string
    - name: Type
      type: string
      required: true
    - name: Spec
      type: map:interface{}
      required: true

