type:
  name: "Config"
  kebab: true
  version: "0.0.1"
  fields:
    - name: Name
      type: string
      required: true
    - name: Version
      type: string
      required: true
    - name: About
      type: string
    - name: DesignDir
      type: string
      default: '"design"'
    - name: DesignPaths
      type: "array:string"
    - name: OutputDir
      type: string
      default: '"."'
    - name: DslConfig
      type: DslConfig
      required: true

