type:
  name: "DslConfig"
  kabob: true
  version: "0.0.1"
  fields:
    - name: Paths
      type: array:string
      required: true
    - name: Default
      type: "array:engine.gen.GeneratorConfig"

