type:
  name: "project"
  kabob: true
  fields:
    - name: config
      type: '*Config'
    - name: available
      type: 'map:*engine.dsl.Dsl'
    - name: design
      type: '*engine.design.Design'
    - name: dsl-map
      type: 'map:*engine.dsl.Dsl'
    - name: plans
      type: 'array:engine.plan.Plan'

  public-functions:

    - name: load
      args:
        - name: filename
          type: string
        - name: generators
          type: "array:string"
      return:
        - name: err
          type: error

    - name: unify
      return:
        - name: errorReport
          type: "array:error"

    - name: plan
      return:
        - name: err
          type: error

    - name: render
      return:
        - name: err
          type: error

    - name: find-available-generators
      args:
        - name: paths
          type: "array:string"
      return:
        - name: err
          type: error

  public-files:
    - name: load
      functions:

        - name: load-default-generators
          return:
            - name: err
              type: error

        - name: load-generators
          args:
            - name: generators
              type: "array:string"
          return:
            - name: err
              type: error

        - name: load-generator-list
          args:
            - name: generators
              type: "array:string"
          return:
            - name: err
              type: error


  private-files:
    - name: template-helpers
      functions:
        - name: register-partials
        - name: add-template-helpers


