type:
  name: "Project"
  kebab: true
  fields:
    - name: Config
      type: '*Config'
    - name: Available
      type: 'map:*engine.dsl.Dsl'
    - name: Design
      type: '*engine.design.Design'
    - name: DslMap
      type: 'map:*engine.dsl.Dsl'
    - name: Plans
      type: 'array:engine.plan.Plan'

  functions:

    - name: Load
      args:
        - name: filename
          type: string
        - name: generators
          type: "array:string"
      return:
        - name: err
          type: error

    - name: Unify
      return:
        - name: errorReport
          type: "array:error"

    - name: Subdesign
      return:
        - name: errorReport
          type: "array:error"

    - name: Plan
      return:
        - name: err
          type: error

    - name: Render
      return:
        - name: err
          type: error

    - name: FindAvailableGenerators
      args:
        - name: paths
          type: "array:string"
      return:
        - name: err
          type: error

  files:
    - name: Load
      functions:

        - name: LoadGenerators
          return:
            - name: err
              type: error

        - name: LoadGenerator
          args:
            - name: generator
              type: "engine.gen.GeneratorConfig"
            - name: dslLookupPaths
              type: "array:string"
          return:
            - name: err
              type: error


    - name: TemplateHelpers
      functions:
        - name: registerPartials
        - name: addTemplateHelpers


